name: Site check

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check site
        run: |
          if curl -s -L -o /dev/null -w "%{http_code}" https://appointment.blsspainrussia.ru/Global/account/login | grep -E "200|302"; then
            curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TG_CHAT_ID }} \
            -d text="Сайт заработал"
          fi
